import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { Package, Pencil, Plus, SlidersHorizontal } from 'lucide-react'
import { Badge, PageHeader, StatCard } from '../components/UI'
import { DataTable, ErrorBanner, Field, FormActions, LoadingPanel, Modal, OrganizationSetup } from '../components/OperationalUI'
import { supabase } from '../lib/supabase'
import { brl, numberBR, unitCostBR } from '../lib/format'
import { useOrganization } from '../lib/useOrganization'

type RecipeOption={recipe_version_id:string;recipe_id:string;name:string;version_number:number;status:string;yield_quantity:number;yield_unit_id:string;yield_unit_symbol:string;total_cost:number;cost_per_yield:number}
type ProductSummary={organization_id:string;product_id:string;name:string;category:string|null;internal_code:string|null;barcode:string|null;recipe_version_id:string|null;recipe_name:string|null;recipe_version_number:number|null;stock_unit_id:string|null;stock_unit_symbol:string;sale_price:number;minimum_stock:number;active:boolean;available:boolean;available_quantity:number;unit_cost:number;stock_value:number;gross_profit_unit:number;gross_margin_percent:number;created_at:string;updated_at:string}
type Unit={id:string;name:string;symbol:string}
type Location={id:string;name:string}

export default function Products(){
  const org=useOrganization(); const [products,setProducts]=useState<ProductSummary[]>([]); const [recipes,setRecipes]=useState<RecipeOption[]>([]); const [locations,setLocations]=useState<Location[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [edit,setEdit]=useState<ProductSummary|null|undefined>(undefined); const [adjust,setAdjust]=useState<ProductSummary|null>(null)
  const load=useCallback(async()=>{if(!supabase||!org.organization)return;setLoading(true);setError('');const oid=org.organization.id;const [p,r,l]=await Promise.all([
    supabase.from('product_stock_summary').select('*').eq('organization_id',oid).order('name'),
    supabase.from('recipe_cost_summary').select('recipe_version_id,recipe_id,name,version_number,status,yield_quantity,yield_unit_id,yield_unit_symbol,total_cost,cost_per_yield').eq('organization_id',oid).eq('status','ativa').order('name'),
    supabase.from('stock_locations').select('id,name').eq('organization_id',oid).eq('active',true).order('name'),
  ]);const e=p.error||r.error||l.error;if(e)setError(e.message);setProducts((p.data??[]) as ProductSummary[]);setRecipes((r.data??[]) as RecipeOption[]);setLocations((l.data??[]) as Location[]);setLoading(false)},[org.organization])
  useEffect(()=>{load()},[load])
  const active=products.filter(p=>p.active).length;const stockQty=products.reduce((s,p)=>s+Number(p.available_quantity||0),0);const stockValue=products.reduce((s,p)=>s+Number(p.stock_value||0),0);const critical=products.filter(p=>p.active&&Number(p.available_quantity||0)<=Number(p.minimum_stock||0)).length
  if(org.loading)return <LoadingPanel/>
  if(!org.organization)return <><PageHeader title="Produtos" description="Cadastre itens vendáveis e conecte produção, estoque e preço."/><OrganizationSetup onCreate={org.bootstrap}/></>
  return <>
    <PageHeader title="Produtos" description="Produtos vendáveis vinculam ficha técnica, custo real, preço e estoque acabado. Produções futuras entram automaticamente no saldo quando a ficha está vinculada." action={<button className="primary" onClick={()=>setEdit(null)}><Plus size={17}/> Novo produto</button>}/>
    <ErrorBanner message={error||org.error}/>
    <div className="stats-grid compact-stats"><StatCard label="Produtos ativos" value={String(active)} helper="Disponíveis no catálogo."/><StatCard label="Saldo acabado" value={numberBR.format(stockQty)} helper="Soma das quantidades produzidas."/><StatCard label="Valor em acabados" value={brl.format(stockValue)} helper="Saldo atual × custo médio real."/><StatCard label="Estoque crítico" value={String(critical)} helper="Produtos no ou abaixo do mínimo."/></div>
    <div className="panel module-panel"><div className="panel-toolbar"><div><h3>Catálogo e estoque acabado</h3><p>O custo usa produção real quando houver; antes da primeira produção, usa o custo padrão da ficha técnica.</p></div><button className="secondary" onClick={load}>Atualizar</button></div>
      {loading?<LoadingPanel text="Carregando produtos…"/>:products.length===0?<div className="empty"><div className="empty-icon"><Package/></div><h3>Nenhum produto cadastrado</h3><p>Crie um produto e vincule a ficha técnica correta. A próxima produção dessa ficha entrará automaticamente no estoque acabado.</p><button className="primary" onClick={()=>setEdit(null)}>Novo produto</button></div>:<DataTable headers={['Produto','Ficha técnica','Custo unit.','Preço','Margem','Estoque','Valor estoque','Status','Ações']}>
        {products.map(p=><tr key={p.product_id}><td><strong>{p.name}</strong><small className="cell-helper">{p.category||'Sem categoria'}{p.internal_code?` • ${p.internal_code}`:''}</small></td><td>{p.recipe_name?<><strong>{p.recipe_name}</strong><small className="cell-helper">v{p.recipe_version_number}</small></>:'—'}</td><td>{unitCostBR(Number(p.unit_cost))}/{p.stock_unit_symbol}</td><td><strong>{brl.format(Number(p.sale_price))}</strong></td><td>{brl.format(Number(p.gross_profit_unit))}<small className="cell-helper">{numberBR.format(Number(p.gross_margin_percent))}%</small></td><td><strong>{numberBR.format(Number(p.available_quantity))} {p.stock_unit_symbol}</strong><small className="cell-helper">mín. {numberBR.format(Number(p.minimum_stock))}</small></td><td>{brl.format(Number(p.stock_value))}</td><td>{productStatus(p)}</td><td><div className="row-actions"><button className="table-action" onClick={()=>setEdit(p)}><Pencil size={14}/> Editar</button><button className="table-action" onClick={()=>setAdjust(p)}><SlidersHorizontal size={14}/> Ajustar</button></div></td></tr>)}
      </DataTable>}
    </div>
    {edit!==undefined&&<ProductModal organizationId={org.organization.id} units={org.units} recipes={recipes} existing={edit||undefined} onClose={()=>setEdit(undefined)} onSaved={async()=>{setEdit(undefined);await load()}}/>}
    {adjust&&<AdjustProductModal product={adjust} locations={locations} onClose={()=>setAdjust(null)} onSaved={async()=>{setAdjust(null);await load()}}/>}
  </>
}

function ProductModal({organizationId,units,recipes,existing,onClose,onSaved}:{organizationId:string;units:Unit[];recipes:RecipeOption[];existing?:ProductSummary;onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState(existing?.name??'');const [category,setCategory]=useState(existing?.category??'');const [internalCode,setInternalCode]=useState(existing?.internal_code??'');const [barcode,setBarcode]=useState(existing?.barcode??'');const [recipeId,setRecipeId]=useState(existing?.recipe_version_id??'');const [stockUnit,setStockUnit]=useState(existing?.stock_unit_id??units.find(u=>u.symbol==='un')?.id??units[0]?.id??'');const [salePrice,setSalePrice]=useState(existing?String(existing.sale_price):'0');const [minimumStock,setMinimumStock]=useState(existing?String(existing.minimum_stock):'0');const [active,setActive]=useState(existing?.active??true);const [available,setAvailable]=useState(existing?.available??true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const recipe=useMemo(()=>recipes.find(r=>r.recipe_version_id===recipeId),[recipes,recipeId]);const unitCost=Number(existing?.unit_cost||recipe?.cost_per_yield||0);const price=Number(salePrice||0);const profit=price-unitCost;const margin=price>0?profit/price*100:0
  useEffect(()=>{if(recipe?.yield_unit_id)setStockUnit(recipe.yield_unit_id)},[recipe?.yield_unit_id])
  async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setSaving(true);setError('');const common={p_name:name,p_category:category,p_internal_code:internalCode,p_barcode:barcode,p_recipe_version_id:recipeId||null,p_stock_unit_id:stockUnit,p_sale_price:Number(salePrice||0),p_minimum_stock:Number(minimumStock||0),p_active:active,p_available:available};const result=existing?await supabase.rpc('update_product_catalog_item',{p_product_id:existing.product_id,...common}):await supabase.rpc('create_product_catalog_item',{p_organization_id:organizationId,...common});if(result.error){setError(result.error.message);setSaving(false);return}setSaving(false);onSaved()}
  return <Modal title={existing?`Editar produto — ${existing.name}`:'Novo produto'} onClose={onClose} wide><form onSubmit={submit} className="form-grid"><div className="form-grid two-cols"><Field label="Nome"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Bolo de chocolate" required/></Field><Field label="Categoria"><input value={category??''} onChange={e=>setCategory(e.target.value)} placeholder="Ex.: Bolos"/></Field><Field label="Código interno"><input value={internalCode??''} onChange={e=>setInternalCode(e.target.value)} placeholder="Ex.: BOL-001"/></Field><Field label="Código de barras"><input value={barcode??''} onChange={e=>setBarcode(e.target.value)} placeholder="Opcional"/></Field><Field label="Ficha técnica vinculada"><select value={recipeId} onChange={e=>setRecipeId(e.target.value)}><option value="">Sem ficha técnica</option>{recipes.map(r=><option key={r.recipe_version_id} value={r.recipe_version_id}>{r.name} • v{r.version_number} • {numberBR.format(Number(r.yield_quantity))} {r.yield_unit_symbol} • {unitCostBR(Number(r.cost_per_yield))}/{r.yield_unit_symbol}</option>)}</select></Field><Field label="Unidade de estoque" hint={recipe?'Definida pelo rendimento da ficha técnica selecionada.':undefined}><select value={stockUnit} onChange={e=>setStockUnit(e.target.value)} disabled={!!recipe}>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.symbol})</option>)}</select></Field><Field label="Preço de venda"><input type="number" min="0" step="0.01" value={salePrice} onChange={e=>setSalePrice(e.target.value)} required/></Field><Field label="Estoque mínimo"><input type="number" min="0" step="any" value={minimumStock} onChange={e=>setMinimumStock(e.target.value)} required/></Field><Field label="Custo unitário"><div className="cost-display"><strong>{unitCostBR(unitCost)}</strong><span>{recipe?`Ficha ${recipe.name} v${recipe.version_number}`:'Sem ficha vinculada'}</span></div></Field><Field label="Margem bruta"><div className="cost-display"><strong>{brl.format(profit)}</strong><span>{numberBR.format(margin)}% do preço de venda</span></div></Field></div><div className="toggle-row"><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Produto ativo</label><label><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> Disponível para venda</label></div><ErrorBanner message={error}/><FormActions><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando…':'Salvar produto'}</button></FormActions></form></Modal>
}

function AdjustProductModal({product,locations,onClose,onSaved}:{product:ProductSummary;locations:Location[];onClose:()=>void;onSaved:()=>void}){
  const [locationId,setLocationId]=useState(locations[0]?.id??'');const [quantity,setQuantity]=useState('');const [unitCost,setUnitCost]=useState(String(product.unit_cost||0));const [reason,setReason]=useState('');const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;const qty=Number(quantity||0);if(qty===0){setError('Informe uma quantidade positiva para entrada ou negativa para saída.');return}setSaving(true);setError('');const {error:rpcError}=await supabase.rpc('adjust_product_stock',{p_product_id:product.product_id,p_stock_location_id:locationId,p_quantity:qty,p_unit_cost:Number(unitCost||0),p_reason:reason});if(rpcError){setError(rpcError.message);setSaving(false);return}setSaving(false);onSaved()}
  return <Modal title={`Ajustar estoque — ${product.name}`} onClose={onClose}><form onSubmit={submit} className="form-grid"><div className="confirm-note"><Package/><div><strong>Saldo atual: {numberBR.format(Number(product.available_quantity))} {product.stock_unit_symbol}</strong><p>Use quantidade positiva para entrada e negativa para saída. O ajuste fica registrado no histórico.</p></div></div><Field label="Local de estoque"><select value={locationId} onChange={e=>setLocationId(e.target.value)} required>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label={`Quantidade (${product.stock_unit_symbol})`}><input type="number" step="any" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="Ex.: 5 ou -2" required/></Field><Field label={`Custo unitário (${product.stock_unit_symbol})`} hint="Usado em ajustes de entrada. Saídas utilizam o custo médio atual."><input type="number" min="0" step="any" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/></Field><Field label="Motivo"><textarea rows={3} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: inventário físico" required/></Field><ErrorBanner message={error}/><FormActions><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Registrando…':'Registrar ajuste'}</button></FormActions></form></Modal>
}

function productStatus(p:ProductSummary){if(!p.active)return <Badge>Inativo</Badge>;if(!p.available)return <Badge tone="warning">Indisponível</Badge>;if(Number(p.available_quantity)<=Number(p.minimum_stock))return <Badge tone="danger">Crítico</Badge>;return <Badge tone="success">Disponível</Badge>}
