import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { ChefHat, Plus, Trash2 } from 'lucide-react'
import { Badge, PageHeader, StatCard } from '../components/UI'
import { DataTable, ErrorBanner, Field, FormActions, LoadingPanel, Modal, OrganizationSetup } from '../components/OperationalUI'
import { supabase } from '../lib/supabase'
import { brl, numberBR, unitCostBR } from '../lib/format'
import { useOrganization } from '../lib/useOrganization'

type Ingredient={id:string;name:string;base_unit_id:string;unit_symbol:string;average_cost:number;available_quantity:number}
type RecipeSummary={organization_id:string;recipe_id:string;name:string;category:string|null;active:boolean;recipe_version_id:string;version_number:number;status:'rascunho'|'ativa'|'arquivada';yield_quantity:number;yield_unit_id:string;yield_unit_symbol:string;instructions:string|null;total_cost:number;cost_per_yield:number;ingredient_count:number;created_at:string}
type FormItem={ingredient_base_id:string;quantity:string;loss_percent:string}

const emptyItem=():FormItem=>({ingredient_base_id:'',quantity:'',loss_percent:'0'})

export default function Recipes(){
  const org=useOrganization(); const [recipes,setRecipes]=useState<RecipeSummary[]>([]); const [ingredients,setIngredients]=useState<Ingredient[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [modal,setModal]=useState<{recipe?:RecipeSummary;items?:FormItem[]}|null>(null)
  const load=useCallback(async()=>{if(!supabase||!org.organization)return;setLoading(true);setError('');const oid=org.organization.id;const [r,i]=await Promise.all([
    supabase.from('recipe_cost_summary').select('*').eq('organization_id',oid).order('created_at',{ascending:false}),
    supabase.from('ingredient_stock_summary').select('ingredient_base_id,name,unit_symbol,average_cost,available_quantity').eq('organization_id',oid).order('name'),
  ]);const baseResult=await supabase.from('ingredient_bases').select('id,base_unit_id').eq('organization_id',oid).eq('active',true);const err=r.error||i.error||baseResult.error;if(err)setError(err.message);const baseMap=new Map((baseResult.data??[]).map(x=>[x.id,x.base_unit_id]));setRecipes((r.data??[]) as RecipeSummary[]);setIngredients(((i.data??[]) as any[]).map(x=>({...x,id:x.ingredient_base_id,base_unit_id:baseMap.get(x.ingredient_base_id)||''})) as Ingredient[]);setLoading(false)},[org.organization])
  useEffect(()=>{load()},[load])
  const current=useMemo(()=>{const map=new Map<string,RecipeSummary>();for(const r of recipes){const prev=map.get(r.recipe_id);if(!prev||Number(r.version_number)>Number(prev.version_number))map.set(r.recipe_id,r)}return [...map.values()]},[recipes])
  const active=current.filter(r=>r.status==='ativa').length;const drafts=current.filter(r=>r.status==='rascunho').length;const totalCost=current.reduce((a,r)=>a+Number(r.total_cost||0),0);const withoutCost=current.filter(r=>Number(r.total_cost||0)===0).length
  async function newVersion(recipe:RecipeSummary){if(!supabase)return;setError('');const {data,error:e}=await supabase.from('recipe_items').select('ingredient_base_id,quantity,loss_percent').eq('recipe_version_id',recipe.recipe_version_id).eq('item_type','insumo').order('created_at');if(e){setError(e.message);return}setModal({recipe,items:(data??[]).map(x=>({ingredient_base_id:x.ingredient_base_id,quantity:String(x.quantity),loss_percent:String(x.loss_percent)}))})}
  if(org.loading)return <LoadingPanel/>
  if(!org.organization)return <><PageHeader title="Receitas" description="Crie fichas técnicas e calcule custos a partir dos insumos."/><OrganizationSetup onCreate={org.bootstrap}/></>
  return <>
    <PageHeader title="Receitas / Fichas Técnicas" description="Custos calculados pelo custo médio atual dos insumos. Cada alteração estrutural pode gerar uma nova versão da ficha." action={<button className="primary" onClick={()=>setModal({})}><Plus size={17}/> Nova receita</button>}/>
    <ErrorBanner message={error||org.error}/>
    <div className="stats-grid compact-stats"><StatCard label="Receitas" value={String(current.length)} helper="Fichas técnicas cadastradas."/><StatCard label="Ativas" value={String(active)} helper={`${drafts} em rascunho.`}/><StatCard label="Custo das fichas" value={brl.format(totalCost)} helper="Soma do custo atual das versões mais recentes."/><StatCard label="Sem custo" value={String(withoutCost)} helper="Receitas com insumos sem custo de estoque."/></div>
    <div className="panel module-panel"><div className="panel-toolbar"><div><h3>Fichas técnicas</h3><p>Quantidade dos ingredientes é registrada sempre na unidade-base do insumo.</p></div><button className="secondary" onClick={load}>Atualizar</button></div>
      {loading?<LoadingPanel text="Carregando receitas…"/>:current.length===0?<div className="empty"><div className="empty-icon"><ChefHat/></div><h3>Nenhuma receita cadastrada</h3><p>Cadastre uma ficha técnica para calcular custo, rendimento e, depois, consumo de produção.</p><button className="primary" onClick={()=>setModal({})}>Nova receita</button></div>:<DataTable headers={['Receita','Versão','Rendimento','Ingredientes','Custo total','Custo por rendimento','Status','Ações']}>
        {current.map(r=><tr key={r.recipe_id}><td><strong>{r.name}</strong><small className="cell-helper">{r.category||'Sem categoria'}</small></td><td>v{r.version_number}</td><td>{numberBR.format(Number(r.yield_quantity))} {r.yield_unit_symbol}</td><td>{r.ingredient_count}</td><td><strong>{brl.format(Number(r.total_cost))}</strong></td><td>{unitCostBR(Number(r.cost_per_yield))}/{r.yield_unit_symbol}</td><td>{statusBadge(r.status)}</td><td><button className="table-action" onClick={()=>newVersion(r)}><Plus size={15}/> Nova versão</button></td></tr>)}
      </DataTable>}
    </div>
    {modal&&<RecipeModal organizationId={org.organization.id} units={org.units} ingredients={ingredients} existing={modal.recipe} initialItems={modal.items} onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);await load()}}/>}
  </>
}

function RecipeModal({organizationId,units,ingredients,existing,initialItems,onClose,onSaved}:{organizationId:string;units:{id:string;name:string;symbol:string}[];ingredients:Ingredient[];existing?:RecipeSummary;initialItems?:FormItem[];onClose:()=>void;onSaved:()=>void}){
  const [name,setName]=useState(existing?.name??'');const [category,setCategory]=useState(existing?.category??'');const [yieldQty,setYieldQty]=useState(existing?String(existing.yield_quantity):'1');const [yieldUnit,setYieldUnit]=useState(existing?.yield_unit_id??units.find(u=>u.symbol==='un')?.id??units[0]?.id??'');const [instructions,setInstructions]=useState(existing?.instructions??'');const [status,setStatus]=useState<'rascunho'|'ativa'>(existing?.status==='ativa'?'ativa':'rascunho');const [items,setItems]=useState<FormItem[]>(initialItems?.length?initialItems:[emptyItem()]);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
  const ingredientMap=useMemo(()=>new Map(ingredients.map(i=>[i.id,i])),[ingredients]);
  const cost=useMemo(()=>items.reduce((total,item)=>{const ing=ingredientMap.get(item.ingredient_base_id);const qty=Number(item.quantity||0);const loss=Math.min(99.9999,Math.max(0,Number(item.loss_percent||0)));const gross=loss>=100?0:qty/(1-loss/100);return total+gross*Number(ing?.average_cost||0)},0),[items,ingredientMap]);
  function update(index:number,patch:Partial<FormItem>){setItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item))}
  async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setError('');if(items.some(i=>!i.ingredient_base_id||Number(i.quantity)<=0)){setError('Preencha todos os insumos com quantidade maior que zero.');return}setSaving(true);const payload=items.map(i=>({ingredient_base_id:i.ingredient_base_id,quantity:Number(i.quantity),loss_percent:Number(i.loss_percent||0)}));const result=existing?await supabase.rpc('create_recipe_version',{p_recipe_id:existing.recipe_id,p_yield_quantity:Number(yieldQty),p_yield_unit_id:yieldUnit,p_instructions:instructions,p_status:status,p_items:payload}):await supabase.rpc('create_recipe_with_version',{p_organization_id:organizationId,p_name:name,p_category:category,p_yield_quantity:Number(yieldQty),p_yield_unit_id:yieldUnit,p_instructions:instructions,p_status:status,p_items:payload});if(result.error){setError(result.error.message);setSaving(false);return}setSaving(false);onSaved()}
  return <Modal title={existing?`Nova versão — ${existing.name}`:'Nova receita'} onClose={onClose} wide><form onSubmit={submit} className="form-grid">
    <div className="form-grid two-cols"><Field label="Nome"><input value={name} onChange={e=>setName(e.target.value)} disabled={!!existing} placeholder="Ex.: Bolo de chocolate" required/></Field><Field label="Categoria"><input value={category??''} onChange={e=>setCategory(e.target.value)} disabled={!!existing} placeholder="Ex.: Bolos"/></Field><Field label="Rendimento"><input type="number" min="0.000001" step="any" value={yieldQty} onChange={e=>setYieldQty(e.target.value)} required/></Field><Field label="Unidade do rendimento"><select value={yieldUnit} onChange={e=>setYieldUnit(e.target.value)} required>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.symbol})</option>)}</select></Field><Field label="Status inicial"><select value={status} onChange={e=>setStatus(e.target.value as 'rascunho'|'ativa')}><option value="rascunho">Rascunho</option><option value="ativa">Ativa</option></select></Field><Field label="Custo estimado"><div className="cost-display"><strong>{brl.format(cost)}</strong><span>{Number(yieldQty)>0?`${unitCostBR(cost/Number(yieldQty))} por rendimento`:'Informe o rendimento'}</span></div></Field></div>
    <Field label="Modo de preparo / observações"><textarea rows={3} value={instructions??''} onChange={e=>setInstructions(e.target.value)} placeholder="Etapas, temperatura, ponto, observações internas…"/></Field>
    <div className="recipe-items"><div className="section-title"><div><strong>Ingredientes</strong><span>Perda aumenta a quantidade bruta necessária e o custo calculado.</span></div><button type="button" className="secondary" onClick={()=>setItems(v=>[...v,emptyItem()])}><Plus size={15}/> Adicionar</button></div>
      {items.map((item,index)=>{const ing=ingredientMap.get(item.ingredient_base_id);const qty=Number(item.quantity||0);const loss=Number(item.loss_percent||0);const gross=loss>=100?0:qty/(1-loss/100);const line=gross*Number(ing?.average_cost||0);return <div className="recipe-item-row" key={index}><div className="recipe-row-index">{index+1}</div><Field label="Insumo"><select value={item.ingredient_base_id} onChange={e=>update(index,{ingredient_base_id:e.target.value})} required><option value="">Selecione</option>{ingredients.map(i=><option key={i.id} value={i.id}>{i.name} — {i.unit_symbol}</option>)}</select></Field><Field label={`Quantidade ${ing?`(${ing.unit_symbol})`:''}`}><input type="number" min="0.000001" step="any" value={item.quantity} onChange={e=>update(index,{quantity:e.target.value})} required/></Field><Field label="Perda %"><input type="number" min="0" max="99.99" step="any" value={item.loss_percent} onChange={e=>update(index,{loss_percent:e.target.value})}/></Field><div className="recipe-cost-box"><span>Custo médio</span><strong>{unitCostBR(Number(ing?.average_cost||0))}/{ing?.unit_symbol||'—'}</strong><small>Bruto: {numberBR.format(gross)} {ing?.unit_symbol||''}</small></div><div className="recipe-cost-box"><span>Custo do item</span><strong>{brl.format(line)}</strong><small>Saldo: {numberBR.format(Number(ing?.available_quantity||0))} {ing?.unit_symbol||''}</small></div><button type="button" className="danger-icon" onClick={()=>setItems(v=>v.length===1?[emptyItem()]:v.filter((_,i)=>i!==index))} aria-label="Remover"><Trash2 size={18}/></button></div>})}
    </div>
    <ErrorBanner message={error}/><FormActions><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button className="primary" disabled={saving}>{saving?'Salvando…':existing?'Criar nova versão':'Salvar receita'}</button></FormActions>
  </form></Modal>
}

function statusBadge(status:RecipeSummary['status']){if(status==='ativa')return <Badge tone="success">Ativa</Badge>;if(status==='rascunho')return <Badge tone="warning">Rascunho</Badge>;return <Badge>Arquivada</Badge>}
